# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: t.j.neep@bham.ac.uk
author_name: Tom Neep
has_binder: true
has_settings: false
kind: frontend-and-server
labextension_name: climb_usage_extension
project_short_description: A JupyterLab extension to query CLIMB resource usage
python_name: climb_usage_extension
repository: ''
test: false

